language: perl

perl:
  - "5.16"
  - "5.20"

env:
    - PERL_CPANM_OPT=-n
sudo: false

cache:
    directories :
        - /home/travis/perl5/perlbrew/perls/5.20/lib/site_perl
        - /home/travis/perl5/perlbrew/perls/5.16/lib/site_perl

