---
abstract: 'The Useful Backend API'
author:
  - unknown
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
  Module::Build::Mojolicious: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tuba
provides:
  Tuba:
    file: lib/Tuba.pm
    version: 0.31
  Tuba::Article:
    file: lib/Tuba/Article.pm
    version: 0
  Tuba::Auth:
    file: lib/Tuba/Auth.pm
    version: 0
  Tuba::Chapter:
    file: lib/Tuba/Chapter.pm
    version: 0
  Tuba::Controller:
    file: lib/Tuba/Controller.pm
    version: 0
  Tuba::DB:
    file: lib/Tuba/DB.pm
    version: 0
  Tuba::DB::Object:
    file: lib/Tuba/DB/Object.pm
    version: 0
  Tuba::DB::Object::Article:
    file: lib/Tuba/DB/Mixin/Object/Article.pm
    version: 0
  Tuba::DB::Object::Chapter:
    file: lib/Tuba/DB/Mixin/Object/Chapter.pm
    version: 0
  Tuba::DB::Object::Figure:
    file: lib/Tuba/DB/Mixin/Object/Figure.pm
    version: 0
  Tuba::DB::Object::Image:
    file: lib/Tuba/DB/Mixin/Object/Image.pm
    version: 0
  Tuba::DB::Object::Organization:
    file: lib/Tuba/DB/Mixin/Object/Organization.pm
    version: 0
  Tuba::DB::Object::Person:
    file: lib/Tuba/DB/Mixin/Object/Person.pm
    version: 0
  Tuba::DB::Objects:
    file: lib/Tuba/DB/Objects.pm
    version: 0
  Tuba::Dataset:
    file: lib/Tuba/Dataset.pm
    version: 0
  Tuba::Figure:
    file: lib/Tuba/Figure.pm
    version: 0
  Tuba::File:
    file: lib/Tuba/File.pm
    version: 0
  Tuba::Finding:
    file: lib/Tuba/Finding.pm
    version: 0
  Tuba::Image:
    file: lib/Tuba/Image.pm
    version: 0
  Tuba::Journal:
    file: lib/Tuba/Journal.pm
    version: 0
  Tuba::Log:
    file: lib/Tuba/Log.pm
    version: 0
  Tuba::Organization:
    file: lib/Tuba/Organization.pm
    version: 0
  Tuba::Person:
    file: lib/Tuba/Person.pm
    version: 0
  Tuba::Plugin::Auth:
    file: lib/Tuba/Plugin/Auth.pm
    version: 0
  Tuba::Plugin::Db:
    file: lib/Tuba/Plugin/Db.pm
    version: 0
  Tuba::Report:
    file: lib/Tuba/Report.pm
    version: 0
requires:
  DBIx::Custom: 0
  DBIx::Simple: 0
  Date::Parse: 0
  File::ShareDir: 1.00
  Mojolicious: 4.14
  Mojolicious::Plugin::YamlConfig: 0
  Rose::DB::Object: 0
  SQL::Abstract: 0
  SQL::Interp: 0
  YAML::Syck: 0
  YAML::XS: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.31
