---
abstract: 'The Useful Backend API'
author:
  - unknown
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
  Module::Build::Mojolicious: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tuba
provides:
  Tuba:
    file: lib/Tuba.pm
    version: 0.48
  Tuba::Article:
    file: lib/Tuba/Article.pm
  Tuba::Auth:
    file: lib/Tuba/Auth.pm
  Tuba::Chapter:
    file: lib/Tuba/Chapter.pm
  Tuba::Controller:
    file: lib/Tuba/Controller.pm
  Tuba::Converter:
    file: lib/Tuba/Converter.pm
  Tuba::DB:
    file: lib/Tuba/DB.pm
  Tuba::DB::Object:
    file: lib/Tuba/DB/Object.pm
  Tuba::DB::Object::Article:
    file: lib/Tuba/DB/Mixin/Object/Article.pm
  Tuba::DB::Object::Chapter:
    file: lib/Tuba/DB/Mixin/Object/Chapter.pm
  Tuba::DB::Object::Chapter::Manager:
    file: lib/Tuba/DB/Mixin/Object/Chapter/Manager.pm
  Tuba::DB::Object::Contributor:
    file: lib/Tuba/DB/Mixin/Object/Contributor.pm
  Tuba::DB::Object::Figure:
    file: lib/Tuba/DB/Mixin/Object/Figure.pm
  Tuba::DB::Object::Figure::Manager:
    file: lib/Tuba/DB/Mixin/Object/Figure/Manager.pm
  Tuba::DB::Object::File:
    file: lib/Tuba/DB/Mixin/Object/File.pm
  Tuba::DB::Object::Finding:
    file: lib/Tuba/DB/Mixin/Object/Finding.pm
  Tuba::DB::Object::Finding::Manager:
    file: lib/Tuba/DB/Mixin/Object/Finding/Manager.pm
  Tuba::DB::Object::Image:
    file: lib/Tuba/DB/Mixin/Object/Image.pm
  Tuba::DB::Object::Journal:
    file: lib/Tuba/DB/Mixin/Object/Journal.pm
  Tuba::DB::Object::Keyword:
    file: lib/Tuba/DB/Mixin/Object/Keyword.pm
  Tuba::DB::Object::Manager:
    file: lib/Tuba/DB/Object/Manager.pm
  Tuba::DB::Object::Organization:
    file: lib/Tuba/DB/Mixin/Object/Organization.pm
  Tuba::DB::Object::Person:
    file: lib/Tuba/DB/Mixin/Object/Person.pm
  Tuba::DB::Object::Publication:
    file: lib/Tuba/DB/Mixin/Object/Publication.pm
  Tuba::DB::Object::Report::Manager:
    file: lib/Tuba/DB/Mixin/Object/Report/Manager.pm
  Tuba::DB::Objects:
    file: lib/Tuba/DB/Objects.pm
  Tuba::Dataset:
    file: lib/Tuba/Dataset.pm
  Tuba::Figure:
    file: lib/Tuba/Figure.pm
  Tuba::File:
    file: lib/Tuba/File.pm
  Tuba::Finding:
    file: lib/Tuba/Finding.pm
  Tuba::Image:
    file: lib/Tuba/Image.pm
  Tuba::Importer:
    file: lib/Tuba/Importer.pm
  Tuba::Importer::Processor:
    file: lib/Tuba/Importer/Processor.pm
  Tuba::Importer::Processor::Ant:
    file: lib/Tuba/Importer/Processor/Ant.pm
  Tuba::Importer::Processor::Datasets:
    file: lib/Tuba/Importer/Processor/Datasets.pm
  Tuba::Importer::Processor::Findings:
    file: lib/Tuba/Importer/Processor/Findings.pm
  Tuba::Importer::Processor::Journals:
    file: lib/Tuba/Importer/Processor/Journals.pm
  Tuba::Journal:
    file: lib/Tuba/Journal.pm
  Tuba::Log:
    file: lib/Tuba/Log.pm
  Tuba::Organization:
    file: lib/Tuba/Organization.pm
  Tuba::Person:
    file: lib/Tuba/Person.pm
  Tuba::Plugin::Auth:
    file: lib/Tuba/Plugin/Auth.pm
  Tuba::Plugin::Db:
    file: lib/Tuba/Plugin/Db.pm
  Tuba::Publication:
    file: lib/Tuba/Publication.pm
  Tuba::Report:
    file: lib/Tuba/Report.pm
  Tuba::Search:
    file: lib/Tuba/Search.pm
requires:
  Algorithm::Permute: 0
  Crypt::OpenSSL::RSA: 0
  DBIx::Custom: 0
  DBIx::Simple: 0
  Date::Parse: 0
  File::ShareDir: 1.00
  JSON::WebToken: 0
  JSON::XS: 0
  Mojolicious: 4.14
  Mojolicious::Plugin::YamlConfig: 0
  Pg::hstore: 0
  Rose::DB::Object: 0
  SQL::Abstract: 0
  SQL::Interp: 0
  YAML::Syck: 0
  YAML::XS: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.48
