---
abstract: 'The Useful Backend API'
author:
  - unknown
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tuba
provides:
  Tuba:
    file: lib/Tuba.pm
    version: 0.06
requires:
  DBIx::Simple: 0
  Mojolicious: 0
  Mojolicious::Plugin::YamlConfig: 0
  Rose::DB::Object: 0
  SQL::Abstract: 0
  SQL::Interp: 0
  YAML::Syck: 0
  YAML::XS: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
